config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/application/_navbar.html.erb
<nav class="navbar bg-light">
  <div class="container-fluid">
    <%= link_to 'Wikinimous', articles_path %>
    <%= link_to 'New Article', new_article_path, class: 'btn btn-primary' %>
  </div>
</nav>

app/views/articles/edit.html.erb
<h1>edit</h1>

app/views/articles/index.html.erb
<div class="f-flex flex-column gap-4">
  <% @articles.each do |article| %>
    <div class="card p-3">
      <%= link_to article.title, article_path(article), class: 'fs-1 text-decoration-none' %>
      <p><%= article.content %></p>
    </div>
  <% end %>
</div>

app/views/articles/show.html.erb
<div class="d-flex gap-2">
  <h1><%= @article.title %></h1>
  <%= link_to edit_article_path(@article) do %>
    <i class="fa fa-pencil"></i>
  <% end %>
  <%= link_to article_path(@article),
   data: { data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} } do %>
     <i class="fa fa-trash-o"></i>
  <% end %>
</div>

<p><%= @article.content %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kalam:wght@300;700&family=Lora:ital@0;1&family=Montserrat:wght@300;700&family=Roboto+Slab:wght@300;400&family=Shadows+Into+Light&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'application/navbar'%>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>